---@type vim.lsp.Config
return {
	-- cmd = { "ansible-language-server", "--stdio" },
	-- filetypes = { "yaml", "yml", "ansible" },
	-- root_markers = { "playbooks", "ansible.cfg", ".ansible-lint" },
	-- settings = {
	-- 	ansible = {
	-- 		ansible = {
	-- 			path = "ansible",
	-- 		},
	-- 		executionEnvironment = {
	-- 			enabled = false,
	-- 		},
	-- 		python = {
	-- 			interpreterPath = "python",
	-- 		},
	-- 		validation = {
	-- 			enabled = true,
	-- 			lint = {
	-- 				enabled = true,
	-- 				path = "ansible-lint",
	-- 			},
	-- 		},
	-- 	},
	-- },
}
