# schema for defining tmux sessions
# format:
# [[session]]
# name = "sesh-name" # required and unique
#
# [[session.window]] # >= 1 window required per session
# path = "~/path/to/dir" # required, sets pwd
# command = "cmd" # optional, cmd to run
#
# notes:
# first window listed gets focus on launch.
# if a session already exists, tsl switches to it.

[[session]]
name = "website"

[[session.window]]
path = "~/github/website"

[[session.window]]
path = "~/github/website"
command = "zola serve --open"
