add_newline = false
format = """$directory$character"""
right_format = """$all"""
command_timeout = 1000

[character]
disabled = true

[git_branch]
symbol = " "
format = '[$symbol$branch]($style) '
style = 'bold dimmed white'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold dimmed white'
conflicted = 'U'
up_to_date = ''
untracked = '?'
ahead = '+${count}'
diverged = '+${ahead_count}-${behind_count}'
behind = '-${count}'
stashed = '\$'
modified = 'M'
staged = 'S${count}'
renamed = 'R'
deleted = 'D'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = true
style = 'bold dimmed white'
symbol = " "

[bun]
format = '[bun ($version )]($style)'
disabled = false
version_format = 'v${raw}'
style = 'bold dimmed white'

[c]
format = '[$symbol ($version )]($style)'
disabled = false
symbol = ""
version_format = 'v${raw}'
style = 'bold dimmed white'

[docker_context]
format = '[$symbol$context ✓]($style) '
only_with_files = false
symbol = " "
style = "bold dimmed white"

[golang]
format = '[$symbol($version )]($style)'
symbol = ' '
style = 'bold dimmed white'

[hostname]
disabled = false
ssh_only = true
format = 'on [$hostname]($style)'
ssh_symbol = " "
style = "bold dimmed white"

[lua]
format = '[$symbol($version )]($style)'
symbol = " "
style = "bold dimmed white"
disabled = true

[rust]
# format = '[$symbol($version )]($style)'
format = '[rust ($version )]($style)'
symbol = " "
style = "bold dimmed white"

[package]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
pyenv_version_name = false
style = 'bold dimmed white'

[terraform]
format = '[󱁢 $workspace]($style) '

[nodejs]
format = '[$symbol($version )]($style)'
style = 'bold dimmed white'

[cmd_duration]
disabled = true
