##### prompt #####
# previously: format = """$directory$character"""
# previously: right_format = """$all"""
add_newline = false
format = """$character"""
right_format = """$directory$all"""
command_timeout = 1000

[character]
# disabled = true
# symbol list = › λ \$
success_symbol = 'λ'
error_symbol = 'λ'

##### modules #####

[git_branch]
format = '[$branch]($style) '
style = 'bold dimmed white'

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold dimmed white'
conflicted = 'U'
up_to_date = ''
untracked = '?'
ahead = '+${count}'
diverged = '+${ahead_count}-${behind_count}'
behind = '-${count}'
stashed = '\$'
modified = 'M'
staged = 'S${count}'
renamed = 'R'
deleted = 'D'

[docker_context]
format = '[$symbol$context ✓]($style) '
only_with_files = false
symbol = " "
style = "bold dimmed white"

[hostname]
disabled = false
ssh_only = true
format = 'on [$hostname]($style)'
ssh_symbol = " "
style = "bold dimmed white"

[rust]
format = '[rust ($version )]($style)'
style = "bold dimmed white"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "
pyenv_version_name = false
style = 'bold dimmed white'

[terraform]
format = '[󱁢 $workspace]($style) '

[nodejs]
format = '[$symbol($version )]($style)'
style = 'bold dimmed white'

##### disabled #####

[cmd_duration]
disabled = true

[typst]
disabled = true

[package]
disabled = true

[lua]
disabled = true

##### custom #####

[custom.tailscale]
description = 'show if tailscale is up'
when = '~/.local/bin/tailscale-check'
command = 'true'
format = '[󱗼 ]($style) '
style = 'bold dimmed white'
os = 'macos'
