[settings]
color_theme = "base16"
experimental = true
dotfiles.root = "~/github/dotfiles"
dotfiles.default_mode = "symlink"
minimum_release_age = "0s"
auto_update = true

[dotfiles]
"~/.zshrc" = {}
"~/.hushlogin" = {}
"~/.config/*" = "../../.config/*"

[tools]
ffmpeg = "8.1.2"
node = "24"
